# Generated by Django 2.0.6 on 2019-01-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190127_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Agent'),
        ),
    ]
